### ISSUE TITLE
Type Error : cannot concatenate 'str' and 'int' objects

### ISSUE THREAD

**Issue by ChaiBapchya** [BlazingDB/python-connector#5]
```
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from blazingdb import BlazingPyConnector
>>> blazing_connector = BlazingPyConnector(
...   "127.0.0.1",                      # your host, usually localhost
...   "username",                       # your username
...   "password",                               # your password
...   "database_name",  # name of the data base
...   port=8089
... )
Traceback (most recent call last):
  File "<stdin>", line 6, in <module>
  File "/home/chaitanya/.local/lib/python2.7/site-packages/blazingdb/__init__.py", line 22, in __init__
    self.baseurl = self.protocol+'://'+self.host+':'+self.port+self.context
TypeError: cannot concatenate 'str' and 'int' objects

```

**Comment by ChaiBapchya** [comment]
port="8089"
